name: Build Deb Package

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pylucene_build

    - name: Build .deb package
      run: docker run -v $(pwd):/host:rw pylucene_build
    
    - name: Copy artifact
      run: mkdir -p deb && cp -a python-lucene* pylucene_* deb/

    - uses: actions/upload-artifact@v1
      with:
        name: python-lucene_${{ github.sha }}_amd64
        path: deb

    - name: Exports SSH private key
      run: echo "${{ secrets.SSHPrivateKey }}" > id_rsa && chmod 600 id_rsa
    
    - name: Scp artifact
      run: scp -i id_rsa -r dist/ foobar@sdtest.osdn.co.jp:~/
